### ISSUE TITLE
[Suggestion] Average scores

### ISSUE THREAD

**Issue by timothychin** [scoreboarder/suggestions#12]
I'd like to create a scoreboard where the ranking is based on each person's average score rather than total

**Comment by alvarlagerlof** [comment]
Hi, thanks for your suggestion! 

I'd like to inform you that we're deprecating this feedback method. I point you towards our [Discord Support Server](https://discord.gg/eY5rpZ8vrA) where we have a feedback channel. If you could post your feedback there instead, then that would be great!
